### ISSUE TITLE
Create simple Slackbot

### ISSUE THREAD

**Issue by JasonShin** [blursed/blursed_bot#2]
Context:
Create a simple slack bot that does `something`

Aims:
- A socket-based bot
- Run it on your own computer
- Takes in environment variables to figure out credentials
- Just reply to any message on a channel with `Hello, I'm a blursed bot`

Also, figure out what to do after this ticket

**Comment by matt-harvey** [comment]
Using https://github.com/slack-rs/slack-rs. Looks popular and maintained.

Note also https://github.com/slack-rs/slack-rs-api.

**Comment by matt-harvey** [comment]
Useful reference: https://api.slack.com/rtm

**Comment by matt-harvey** [comment]
Actioned by #10.

**Comment by JasonShin** [comment]
Closing
