### ISSUE TITLE
Travis builds sometimes failing

### ISSUE THREAD

**Issue by matt-harvey** [blursed/blursed_bot#7]
It's due to the Travis build being on nightly.

```
error: component 'clippy' for target 'x86_64-unknown-linux-gnu' is unavailable for download for channel nightly
199The command "rustup component add clippy" failed and exited with 1 during .
```

There's a workaround described [here](https://github.com/rust-lang/rust-clippy#travis-ci).

However I'm wondering if we'll have smoother sailing all round if we just target stable Rust only?

**Comment by JasonShin** [comment]
https://github.com/blursed/blursed_bot/blob/master/.travis.yml

Already switched to the stable channel 👍
